stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: "$CI_COMMIT_SHA"  # Using the commit SHA to ensure unique tags
  REGISTRY: docker.io
  IMAGE_NAME: tejirih/helloworld

# Build the Docker image
build:
  stage: build
  script:
    - echo "REGISTRY is $REGISTRY"  # Debugging line to check if REGISTRY is set correctly
    - echo "Logging in to Docker..."
      #    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $REGISTRY
      #    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $REGISTRY  # Authenticate with Docker
    - docker logout
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $REGISTRY
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest

# Test the application (run python directly)
test:
  stage: test
  script:
    - echo "Installing Python..."
    - apt-get update && apt-get install -y python3
    - echo "Running Python script..."
    - python3 -m py_compile helloworld.py
  only:
    - main

# Deploy to Kubernetes
deploy:
  stage: deploy
  image: amazon/aws-cli:latest  # AWS CLI image to authenticate with EKS
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_FILE" | base64 --decode > ~/.kube/config  # Load kubeconfig
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name my-cluster  # Ensure kubectl can authenticate
 
  script:
   # - echo "$KUBECONFIG_FILE" | base64 --decode > ~/.kube/config
    - kubectl config get-contexts  # Debugging: Check if context is set
    - kubectl config use-context arn:aws:eks:eu-north-1:940482437723:cluster/my-cluster
    - kubectl apply -f k8s/deployment.yaml
    - kubectl set image deployment/helloworld-deployment helloworld=$IMAGE_NAME:$IMAGE_TAG -n backend


  only:
    - main

