apiVersion: v1
kind: Pod
metadata:
  name: test-runner
  namespace: test-environment
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: python:3.9  # Using Python base image (or change if needed)
    command: ["/bin/sh", "-c"]
    args:
      - |
        apt update && apt install -y git
        git clone https://github.com/TejiriH/backend-im.git /workspace
        cd /workspace
        pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pytest helloworld.py
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace
  volumes:
  - name: workspace-volume
    emptyDir: {}
