name: Run WebSocket Client

on:
  push:
    branches:
      - main  # Adjust this based on your workflow

jobs:
  websocket-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Ensure it matches your local environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure websockets is included
          pip install websockets  # Install explicitly if missing

      - name: Set Commit ID
        run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV  # Get latest commit ID

      - name: Run WebSocket Client
        env:
          COMMIT_ID: ${{ env.COMMIT_ID }}
        run: python3 client.py
